version: '3.7'

services:
  ubuntu:
    container_name: pytest_ubuntu
    image: pytest_ubuntu
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.ubuntu
      args:
        buildversion: 1
    ports:
      - "3000:3000"
    volumes:
      - ./src:/opt
    tty: true
    command: tail -F /dev/null

  flaskservice:
    build: flask-service
    ports:
      - "5000:5000"
