version: '3.7'

services:
  pytest_ubuntu:
    container_name: pytest_ubuntu
    image: pytest_ubuntu
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.ubuntu.pytest
      args:
        buildversion: 1
    ports:
      - "3000:3000"
    networks:
      net1:
        ipv4_address: 10.5.0.2
    volumes:
      - ./src:/opt
    tty: true
    command: tail -F /dev/null

  flask_service:
    build: flask_service
    ports:
      - "5000:5000"
    networks:
      net1:
        ipv4_address: 10.5.0.3

  web:
    build: nginx
    ports:
      - "80:80"
    networks:
      net1:
        ipv4_address: 10.5.0.4


networks:
  net1:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
